### ISSUE TITLE
About mesh results.

### ISSUE THREAD

**Issue by zhaihongjia** [eriksandstroem/Point-SLAM#10]
Hello, can you provide your mesh results on replica and scannet datasets?

**Comment by eriksandstroem** [comment]
Hi @zhaihongjia,
You can generate those yourself easily and we do not provide them right now for this reason, but we can if you find this to be important. Let me know. To generate the scannet dataset meshes, simply add "scannet" to the "reconstruction_datasets" list in the config file.
