### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by Yiiii19** [eriksandstroem/Point-SLAM#11]
Hi,
thanks for the amazing work!
I would like to ask if you have any tutorial for running the reconstruction on custom dataset?
I have Realsense Camera and running open3D in advance is not a problem as preprocess.
Thanks!

**Comment by unique1i** [comment]
Hi @Yiiii19. We haven't got a tutorial on this. For custom RGBD dataset, we need aligned depth and color images, usually depth is aligned to color, together with poses. If ground truth poses are not available, the pipeline can anchor the world coordinate based on first frame, in this case, the value should be changed to 0 [here](https://github.com/eriksandstroem/Point-SLAM/blob/388d60922053c5ab4b8ae8f0f26d8d73e86d3136/src/Tracker.py#L278) as currently first two poses are initialized using ground truth. 

There's a [tutorial](http://www.open3d.org/docs/release/tutorial/sensor/realsense.html) on capturing RealSense data with Open3D. I can't provide more help on this. Once dataset is ready, the left effort would be on new dataset class to load depth, color and pose as in [line](https://github.com/eriksandstroem/Point-SLAM/blob/388d60922053c5ab4b8ae8f0f26d8d73e86d3136/src/utils/datasets.py#L121) here.
