### ISSUE TITLE
About run

### ISSUE THREAD

**Issue by ywaison** [eriksandstroem/Point-SLAM#16]
Hello, thank you very much for the code, when I configured the environment according to reademe, running the code “python run.py configs/TUM_RGBD/freiburg1_desk.yaml”, I got an error as shown below
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
I can't wait for your advice and help, thank you again！

**Comment by eriksandstroem** [comment]
Hi,
You are welcome!
This error would suggest that you do not have a GPU available as the "torch.cuda.is_available()" evidently returns False. First confirm with some simple tests that you can load torch tensors to the GPU. What does the command "nvidia-smi" return in the terminal?

**Comment by ywaison** [comment]
> Hi, You are welcome! This error would suggest that you do not have a GPU available as the "torch.cuda.is_available()" evidently returns False. First confirm with some simple tests that you can load torch tensors to the GPU. What does the command "nvidia-smi" return in the terminal?

Glad to get your prompt answer, my computer cuda version is as follows
| NVIDIA-SMI 535.72                 Driver Version: 536.45       CUDA Version: 12.2
And I have cuda version 11.3 installed and pytorch version 1.12.1

**Comment by eriksandstroem** [comment]
And what kind of GPU does it list? E.g. how much memory does it have?

**Comment by ywaison** [comment]
> nvidia-smi

![ZI{02QW_9A HX7$_013(P(O](https://github.com/eriksandstroem/Point-SLAM/assets/138007686/e9204e02-d5f1-42ce-b9da-ab3cebf90c0c)

**Comment by eriksandstroem** [comment]
Closing for now.
