### ISSUE TITLE
 not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by ywaison** [eriksandstroem/Point-SLAM#18]
Hello, when I run the code "python run.py configs/TUM_RGBD/freiburg1_desk.yaml", I get another error as shown below
![D8)FFON)MU$J_599)%X {QS](https://github.com/eriksandstroem/Point-SLAM/assets/138007686/9f1ebc36-6a68-4a27-a384-66800037a937)

**Comment by eriksandstroem** [comment]
Hi @ywaison,
Sorry for my late reply. I will look into this shortly as I have seen this issue myself recently. I suggest you experiment on the other scenes for now until we figured out the cause. Hope that is ok!

Sorry for the inconvenience!

**Comment by unique1i** [comment]
A very late update, I tried on local machine and cluster, but could not reproduce this issue on the scene. As the ```add_neural_points``` is executed in another process, the error message here does not indicate which line the error is. If this error persists, could you help make following changes to the ```add_neural_points``` function to get the full error log:
```
import trackback

def add_neural_points(...):
    try:
        # original content
    except Exception as e:
        traceback.print_exc()
        raise e
 ```
Thanks for your understanding.
