### ISSUE TITLE
About the runtime during mapping.

### ISSUE THREAD

**Issue by Zhaohuai-L** [eriksandstroem/Point-SLAM#19]
Hi,
thanks for the amazing work.

I tried to apply this work to real-time reconstruction, but I found that the mapping of each frame was quite time-consuming (Similar to the results in Table 6 which is 9.85s per Frame).
I noticed that this work is a real-time capable dense RGBD SLAM, so may I ask if there are other configurations that better balance accuracy and time?

Best

**Comment by eriksandstroem** [comment]
Hi @Zhaohuai-L ,
Happy to hear the encouraging words! You are correct about the runtime it its default form. You can run faster mappings (see Table 9 in the supplementary) at around 2.3 seconds for mapping a frame. You can do this by changing this variable: https://github.com/eriksandstroem/Point-SLAM/blob/main/configs/point_slam.yaml#L66

We ran the study on Replica, so it is of course tricky to say how this will work if you are using a custom dataset.

Another thing that will increase mapping and tracking speed is to reduce the number of rays that are sampled for each iteration. This can be adjusted here: https://github.com/eriksandstroem/Point-SLAM/blob/main/configs/point_slam.yaml#L60 and here: https://github.com/eriksandstroem/Point-SLAM/blob/main/configs/point_slam.yaml#L35

Note that those config arguments that I linked are the global ones. There can be dataset specific arguments that overwrites the global ones.

Hope this helps!
