### ISSUE TITLE
How to understand the meaning of "Given an estimated camera pose"?

### ISSUE THREAD

**Issue by eggman-1024** [eriksandstroem/Point-SLAM#20]
Hi! Is the initial camera pose here a random number? Or the initial camera position is known?

**Comment by eggman-1024** [comment]
Besides that, I don't understand "but converges to a bounded set of points when no new scene parts are visited."

**Comment by eriksandstroem** [comment]
Hi @eggman-1024,
The initiali camera pose is know and copied from the GT trajectory.

Regarding: "but converges to a bounded set of points when no new scene parts are visited.", we mean that the number of points will be limited i.e. not increase to infinity if you only explore a room for example. The more rooms you explore at once, the more points you will have, but if we revisit an already scanned area, we will likely not add any new points there. Does this help?

**Comment by eggman-1024** [comment]
> Hi @eggman-1024, The initial camera pose is know and copied from the GT trajectory.
> 
> Regarding: "but converges to a bounded set of points when no new scene parts are visited.", we mean that the number of points will be limited i.e. not increase to infinity if you only explore a room for example. The more rooms you explore at once, the more points you will have, but if we revisit an already scanned area, we will likely not add any new points there. Does this help?

Thank you for your answer, but I still have a few questions: when revisiting an already scanned area, how do I make sure I don't add more points there?

**Comment by eriksandstroem** [comment]
We first check if there are already points using the FAISS database in the neighborhood of the proposed point. If there are points already there, we do not add a new one. Does that help?

**Comment by eggman-1024** [comment]
Thank you very much. I understand~
