### ISSUE TITLE
Online (live) scene reconstruction

### ISSUE THREAD

**Issue by nirmalsnair** [eriksandstroem/Point-SLAM#22]
Thanks for sharing the code!

I'm curious if it's possible to execute this in online mode, using an RGBD sensor like RealSense or an iPhone, to iteratively reconstruct the scene?

**Comment by nirmalsnair** [comment]
Thanks for the quick reply!

Sorry for the confusion, I didn't mean to run the reconstruction on the device itself. I was wondering if it's possible to take input from a streaming device like a webcam, iPhone, or RealSense and have the computer running the code reconstruct the scene on the fly, instead of recording and reconstructing later.

**Comment by Atticuszz** [comment]
> Thanks for the quick reply!
> 
> Sorry for the confusion, I didn't mean to run the reconstruction on the device itself. I was wondering if it's possible to take input from a streaming device like a webcam, iPhone, or RealSense and have the computer running the code reconstruct the scene on the fly, instead of recording and reconstructing later.

 the owner comments on YouTube said it runs under gtx with 16Gb in linux machine，so i also wondering that if it could run moble divice real time just as a lower accuary of mapping  and density of point

**Comment by eriksandstroem** [comment]
> Thanks for the quick reply!
> 
> Sorry for the confusion, I didn't mean to run the reconstruction on the device itself. I was wondering if it's possible to take input from a streaming device like a webcam, iPhone, or RealSense and have the computer running the code reconstruct the scene on the fly, instead of recording and reconstructing later.

Sorry for the late reply. We currently do not support streaming from an external device such as an iphone to the PC to reconstruct.

**Comment by eriksandstroem** [comment]
> > Thanks for the quick reply!
> > Sorry for the confusion, I didn't mean to run the reconstruction on the device itself. I was wondering if it's possible to take input from a streaming device like a webcam, iPhone, or RealSense and have the computer running the code reconstruct the scene on the fly, instead of recording and reconstructing later.
> 
> the owner comments on YouTube said it runs under gtx with 16Gb in linux machine，so i also wondering that if it could run moble divice real time just as a lower accuary of mapping and density of point

Hi,
Thanks for your question! This is not something we tested. I believe quite some engineering effort would be critical for low latency applications for example writing the forward and backprop in CUDA.
