### ISSUE TITLE
How to generate video like your homepage?

### ISSUE THREAD

**Issue by 9796l** [eriksandstroem/Point-SLAM#24]
hello,i am very grateful for your work. when i run this code ,i can get  image results.however, i want to get SLAM video like orb-slam2 which has simultaneous mapping and tracking in small windows. it likes the video in your Point-SLAM homepage. how can i get it?

**Comment by eriksandstroem** [comment]
Hi @9796l,
Very sorry for my late reply on this. I am happy you appreciate our work! 

The video gif is done using open3d, but we don't have the code for this here unfortunately.

It is similar to the visualizer used in NICE-SLAM so you can build on top of this one/modify: https://github.com/cvg/nice-slam/blob/master/visualizer.py

Hope this helps!
