### ISSUE TITLE
Question: how to visualize normal map ?

### ISSUE THREAD

**Issue by Jonas7777777** [eriksandstroem/Point-SLAM#26]
Hello Erik,

thanks for opening the source code of your excellent job! Your paper is clear and logical!
1. How do you visualize the normal map of a reconstructed mesh file, like Figure 3 (b) in the paper? Do you use meshlab or write the script by yourself? Can you point it? 
   
3. " The Figure 2: Point-SLAM Architecture." is beautiful and clean. It seems you can rotate the image and add 3D model with culled mesh, which software do you use to make the graph? I think drawio. can not do that.
 
Many thanks for considering my request. ^^
Jonas

**Comment by eriksandstroem** [comment]
Hi Jonas,
Sorry for the delayed reply. Thanks a lot for your kind words!

To reply to your questions:
1. The normal map is visualized with meshlab, but you need an older version. I used 1.3.3. Hope this helps! Then you can change to the normal shader.
2. I simply use powerpoint to make the architecture figure.

Hope this helps!
Erik
