### ISSUE TITLE
No visualizer

### ISSUE THREAD

**Issue by Nefelibata052** [eriksandstroem/Point-SLAM#27]
The program is running normally but there is no visualization.Please tell me how to create a video visual interface like the one you demonstrated.
![2024-02-26 17-42-36屏幕截图](https://github.com/eriksandstroem/Point-SLAM/assets/131857942/bb27c9df-54e2-4bfc-8ea9-5df0386759ff)
![2024-02-26 17-43-00屏幕截图](https://github.com/eriksandstroem/Point-SLAM/assets/131857942/a6a2d6bb-fff5-4f24-977d-ecade5fed95d)

**Comment by eriksandstroem** [comment]
We don't provide an interactive viewer for the SLAM system, but you can use this one as a template and generate a video similar to the one we show: https://github.com/cvg/nice-slam/blob/master/visualizer.py

Hope this helps!
