### ISSUE TITLE
Running evaluating code generated an error

### ISSUE THREAD

**Issue by anghaocheng** [eriksandstroem/Point-SLAM#28]
Thank you very much for sharing this excellent work. I made an error after running it, which was specifically expressed as 3d could not be evaluated. The output is as follows：

===========================
Evaluating room0
===========================

 Successfully evaluated 3D reconstruction.

Traceback (most recent call last):
  File "/data/whc/Point-SLAM-main/src/Mapper.py", line 924, in run
    result_dict = literal_eval(result_dict)
  File "/home/zju231/anaconda3/envs/point-slam/lib/python3.10/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/home/zju231/anaconda3/envs/point-slam/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 0
    
SyntaxError: invalid syntax
Failed to evaluate 3D reconstruction.

How can I fix it

**Comment by eriksandstroem** [comment]
Hi,
Sorry for my late reply. Can you import the evaluation package? i.e. `from evaluate_3d_reconstruction import run_evaluation`?

**Comment by eriksandstroem** [comment]
Any updates here?

**Comment by anghaocheng** [comment]
Thank you very much for your reply. I have tried and can import this package

**Comment by anghaocheng** [comment]
Hello, thank you for your guidance; when I run the following code alone in the terminal,
python src/tools/eval_recon.py --rec_mesh  --gt_mesh  -3d 
 it seems that the evaluation algorithm can run normally; I set gt_mesh to room0.ply and rec_mesh to room0_pred_mesh.ply under the mesh file in output, and it works Evaluated normally;
![)7B(5GWA$)1T02$67BAFH4H](https://github.com/eriksandstroem/Point-SLAM/assets/95737216/eff98f18-ef2e-4e66-9fbc-47b65411523b)


But I found that the recall and F1 indicators are extremely low, and the precision is extremely high; is this due to the very sparse grid in the room0_pred_mesh.ply file, but I only found this one ply file in the output

**Comment by eriksandstroem** [comment]
Hi,
This is indeed a bit odd. Could it be that you are not running on all frames somehow and that this is why the recall is so low? This should not happen though so would be surprised if this is the reason. Since the recall is low, if you look at the reconstructed mesh, can you see that it is not complete?

**Comment by eriksandstroem** [comment]
Ah ok ! Thanks for sharing. If you find out what made this happen, let me know!
