### ISSUE TITLE
Visualization live

### ISSUE THREAD

**Issue by FranciscoGomez90** [eriksandstroem/Point-SLAM#30]
First I want to thank the authors for the incredible work. I managed to run the sample scene of the Replica dataset and the results are very very good.

My question is, how can I enable a live visualization like the one displayed in the video linked in the repository (min ~ 2-53)??

EDIT: I have seen many closed issues about this so I will change my question.

How can I get the estimated pose of the camera after each mapping/tracking step??
Is it in the "cur_c2w" variable of the Mapper.py?

Thank you for you assistance.

**Comment by unique1i** [comment]
Hi @FranciscoGomez90. Thanks for the question. 

The estimated poses are maintained and updated by tracker [here](https://github.com/eriksandstroem/Point-SLAM/blob/6943bef84ce65883673ab801a4613aee9907ecc6/src/Tracker.py#L382), which is also shared to mapper. You can access estimated poses by index.

For the video demo, we used estimated poses, together with intermediate point clouds and meshed scene to make, with the help of open3d. At the time we didn't integrate this visualization into our pipeline.

**Comment by FranciscoGomez90** [comment]
Thank you for the answer!
Can I run the algorithm on my custom data that consists only of depth maps and color images (no pose data)?
Thanks again!

**Comment by unique1i** [comment]
Yes you can, for this please add a dataset class that has same return format [here](https://github.com/eriksandstroem/Point-SLAM/blob/6943bef84ce65883673ab801a4613aee9907ecc6/src/utils/datasets.py#L121), you could use identity matrix for pose just for implmentation purpose. The downside is that result can not be evaluated as ground true pose is not available.

**Comment by FranciscoGomez90** [comment]
That's okay because I do not want to evaluate it but use it for live SLAM on an actual robot.
Let's see what happens. Thank you!

**Comment by omergreenwald** [comment]
@FranciscoGomez90 did you do it on a live robot? will you agree to share your work?
