### ISSUE TITLE
About evaluation result

### ISSUE THREAD

**Issue by hlldy6858** [eriksandstroem/Point-SLAM#31]
Hello，Thank you for your excellent project！
I would like to ask you a question, is the evaluation result output the data in your paper? Such as precision, recall, and F1 value. Because the output of my evaluation result is a bit off, as shown in the figure, is this normal?
![2024-04-22 21-10-42 的屏幕截图](https://github.com/eriksandstroem/Point-SLAM/assets/155211892/1a478dac-413d-4448-83ff-ad55d8479146)

**Comment by eriksandstroem** [comment]
Hi,
Based on your metrics, I would assume that if you look at the mesh, it is not complete i.e. you did not run the reconstruction on all frames in the sequence.

**Comment by eriksandstroem** [comment]
The numbers we report in the paper should be reproducible with the code we provide.

**Comment by hlldy6858** [comment]
yes，you are right.
I am using the room1 dataset and found that there are 4000 frames in it. However, the code only stopped running after 2000 frames. What is the problem causing this？Thank you for your reply
![2024-04-22 21-24-26 的屏幕截图](https://github.com/eriksandstroem/Point-SLAM/assets/155211892/1a1976d3-c7a0-429e-b25a-a1a6f5d772e7)

**Comment by eriksandstroem** [comment]
No, there are only 2000 frames in the sequence. I suspect that your issue is that meshing is only done on few frames, for some reason. 

Before meshing, we render RGBD from the estimated poses. This can be saved. Can you check if these are computed properly?

**Comment by hlldy6858** [comment]
Are you referring to these two trajectory evaluation charts? In addition to this, the results are as follows
![eval_ate_aligned](https://github.com/eriksandstroem/Point-SLAM/assets/155211892/66a985c5-760c-4aa9-ab1b-74baacbb7e2a)
![eval_ate_no_align](https://github.com/eriksandstroem/Point-SLAM/assets/155211892/95a2feff-2b8f-438d-b627-9fbcb8a98605)
![2024-04-23 09-10-18 的屏幕截图](https://github.com/eriksandstroem/Point-SLAM/assets/155211892/865eb0a0-d683-4a96-a8da-7fdabda8b124)

**Comment by eriksandstroem** [comment]
Check the "final_point_cloud.ply" and compare the completeness to the mesh in the "mesh" folder. I suspect that something makes it such that not all frames are integrated during meshing. You can also check the "rendered_image" folder.

**Comment by eriksandstroem** [comment]
Any update here or should I close this issue?

**Comment by hlldy6858** [comment]
Thank you for your concern, I need to move on to something else for various reasons, I will close this issue
