### ISSUE TITLE
Running Problem

### ISSUE THREAD

**Issue by Tianci-Wen** [eriksandstroem/Point-SLAM#37]
Hello, thank you for your excellent work. I encountered some issues while running your code and hope to receive assistance. The code hangs at a certain line in FAISS during runtime, and there are no printed messages. I installed my environment exactly according to your env.yaml file. Can someone help me resolve this issue? I would greatly appreciate it! My code hangs at this line:
neural_point.py line38-40
```
        self.index = faiss.index_cpu_to_gpu(self.resource,
                                            self.cuda_id,
                                            faiss.IndexIVFFlat(faiss.IndexFlatL2(3), 3, self.nlist, faiss.METRIC_L2))
```
My GPU information is as follows:
![image](https://github.com/user-attachments/assets/9d8fe1a7-0105-4799-8136-e2689c4b6d85)

**Comment by eriksandstroem** [comment]
Hi,
Very sorry for the late reply. Did you resolve the issue? I'm afraid I cannot offer any concrete assistance on this as we did not encounter this problem. I would suspect it might be related to specific hardware specific installation setups.

**Comment by Rashfu** [comment]
Same problem on my 3090 GPU with CUDA11.8
