### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by ljjTYJR** [eriksandstroem/Point-SLAM#4]
Hi,

Thanks for the nice work.

May I ask how to visualize the mapping process like what is shown in the github front page?

**Comment by eriksandstroem** [comment]
Hi ljjTYJR,
Thanks a lot. 

We do not provide this functionality, but it is straight forward to do. Simply save the intermediate meshes at regular intervals during runtime with the `meshing.mesh_freq` config option and then make a visualization as a post processing step using the visualization tools from open3d. Does that help?
