### ISSUE TITLE
GPU Memory Requirements and if there is anyway to minimize it

### ISSUE THREAD

**Issue by altineller** [eriksandstroem/Point-SLAM#5]
I followed the instructions on github to run your code. I have a GPU with 6GB of ram, and after processing  more than thousand frames, it failed to allocate memory and crash.

What are the gpu memory requirements?

Is there setting we can change so it can run on lesser gpu ram?

Best Regards.
Can

**Comment by eriksandstroem** [comment]
Hi altineller,
We run all our experiments on a card with 12 GB of memory, so this is why your runs fail. If you don't have access to a GPU with more memory, I would increase the search radius used for adding points to reduce the number of points that are added. Change the config variables `pointcloud.radius_add_min` and `pointcloud.radius_add_max`. E.g. multiply them with a factor of 4. I can not guarantee that you will be within the memory constraints of your GPU though. Hope that helps!
